/** Declaration file generated by dts-gen */

export = javascript_state_machine;

declare function javascript_state_machine(options: any): any;

declare namespace javascript_state_machine {
    const defaults: {
        init: {
            from: string;
            name: string;
        };
        wildcard: string;
    };

    const version: string;

    function apply(instance: any, options: any): any;

    function factory(...args: any[]): any;

}

